[service]
host = "localhost"
port = 4222
gateway_port = 10147
enable_nats_feature = false

[tls]
key_contents = ""
cert_contents = ""
root_cert_contents = ""

[mlsa]
accept = false

[log]
format = "text"
level = "info"

