[mlsa]
accept = false

[service]
host = "localhost"
port = 10130

[logger]
format = "json"
level = "info"

[storage]
teams_database = "chef_teams_service"
database = "chef_authz_service"
user = "authz"
