---
issuer-url: http://localhost:4200/dex
redirect-url: /session/callback
dex-url: http://localhost:4200/dex # this really is dex
signin-url: /signin
client-id: automate-session
client-secret: secret
http-port: 7777
http-listen: 127.0.0.1
log-level: debug
log-format: json
postgres-url: postgresql://session:session@127.0.0.1:15432/chef_session?sslmode=disable
migrations-path: migration/sql/

tls:
  cert_path: ../../../dev/certs/session-service.crt
  key_path: ../../../dev/certs/session-service.key
  root_ca_path: ../../../dev/certs/Chef_Automate_FAKE_Dev.crt
