---

grpc: 0.0.0.0:9094
log-level: debug
log-format: json

tls:
  cert_path: ../../../dev/certs/authz-service.crt
  key_path: ../../../dev/certs/authz-service.key
  root_ca_path: ../../../dev/certs/Chef_Automate_FAKE_Dev.crt
