---
grpc: {{ cfg.service.host }}:{{ cfg.service.port }}
log-level: {{ cfg.logger.level }}
log-format: {{ cfg.logger.format }}

tls:
  cert_path: {{pkg.svc_config_path}}/service.crt
  key_path: {{pkg.svc_config_path}}/service.key
  root_ca_path: {{pkg.svc_config_path}}/root_ca.crt

database: {{cfg.storage.database}}
migrations-path: {{pkg.path}}/migrations
data-migrations-path: {{pkg.path}}/data-migrations

teams-database: {{cfg.storage.teams_database}}
teams-migrations-path: {{ pkg.path }}/teams-migrations
teams-data-migrations-path: {{ pkg.path }}/teams-data-migrations

{{~#eachAlive bind.event-service.members as |event-service|}}
  {{~#if @last}}
event-address: {{event-service.sys.ip}}:{{event-service.cfg.port}}
  {{~/if}}
{{~/eachAlive}}

config: {{pkg.svc_data_path}}/.authz-service.toml
